services:
  frontend:
    build:
      context: ./frontend
      target: development
    networks:
      - internals
    ports:
      - 5173:5173
      # 80:5173 if you want to access the frontend on port 80
      # 443:5173 if you want to access the frontend on port 443
    volumes:
      - ./frontend/src:/app/src

networks:
  internals:
    driver: bridge