services:
  frontend:
    build:
      context: ./frontend
      target: development
    networks:
      - internals
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src

networks:
  internals:
    driver: bridge