# Generated by Django 5.2.12 on 2026-04-11 13:22

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='xp',
        ),
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.JSONField(default=users.models.get_default_synth_settings, help_text='Custom UI and Synth preferences stored as JSON.'),
        ),
    ]
