# Generated by Django 5.2.12 on 2026-04-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_level_profile_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='settings',
            new_name='def_settings',
        ),
    ]
